package by.krivorot.ishop.command;

public enum CommandName {
	AUTHORIZATION, 
	REGISTRATION,
	GO_TO_MAIN,
	GO_TO_LOGIN,
	CHANGE_FORM,
	CHANGE_LOCALE,
	SIGN_OUT,
	GO_TO_PERSONAL,
	EDIT_USER_DATA,
	GO_TO_CART,
	GO_TO_PRODUCT,
	GO_TO_CATALOG,
	DELETE_FROM_CART,
	GO_TO_PRODUCT_LIST,
	ADD_TO_CART
}
